// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4CodeGenerator.MSSQL2CSHARP.Templates.SQLSERVER.NETCORE.CSHARP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using T4CodeGenerator.MSSQL2CSHARP.Database;
    using T4CodeGenerator.MSSQL2CSHARP.Helpers;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class ApiEntityController : ApiEntityControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
      
// Se repite por cada tabla en la base de datos
string tableName = Configuration.TableName;

            
            #line default
            #line hidden
            this.Write("  \r\n\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;\r\nusing Mic" +
                    "rosoft.AspNetCore.Mvc;\r\nusing Microsoft.AspNetCore.Authentication;\r\nusing AutoMa" +
                    "pper;\r\nusing Core.Services;\r\n\r\nnamespace Api.Endpoints.");
            
            #line 13 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    [Route(\"api/[controller]\")]\r\n    [ApiController]\r\n    public partial cla" +
                    "ss ");
            
            #line 17 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Controller : ControllerBase\r\n    {\r\n        private readonly I");
            
            #line 19 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Service _");
            
            #line 19 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service;\r\n        private readonly IMapper _mapper;\r\n\r\n        public ");
            
            #line 22 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Controller(I");
            
            #line 22 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Service ");
            
            #line 22 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service, IMapper mapper)\r\n        {\r\n            this._mapper = mapper;\r\n        " +
                    "    this._");
            
            #line 25 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service = ");
            
            #line 25 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service;\r\n        }\r\n\r\n        [HttpGet(\"\")]\r\n        public async Task<ActionRes" +
                    "ult<IEnumerable<Response.List.");
            
            #line 29 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("ItemList>>> GetAll()\r\n        {\r\n            var ");
            
            #line 31 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Collection = await _");
            
            #line 31 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetAll();\r\n            \r\n            var getAllResponse = _mapper.Map<IEn" +
                    "umerable<Core.Models.");
            
            #line 33 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(">, IEnumerable<Response.List.");
            
            #line 33 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("ItemList>>(");
            
            #line 33 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Collection);\r\n\r\n            return Ok(getAllResponse);\r\n        }\r\n\r\n        [Htt" +
                    "pGet(\"paged\")]\r\n        public async Task<ActionResult<IEnumerable<Response.List" +
                    ".");
            
            #line 39 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("ItemList>>> GetPaginated(int page, int pageSize, string order, string sort)\r\n    " +
                    "    {\r\n            ObjectResult result = null;\r\n\r\n            if (page >= 0 && p" +
                    "ageSize >= 1 && order != null && order != null)\r\n            {\r\n                " +
                    "var ");
            
            #line 45 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Collection = await _");
            
            #line 45 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetPaged(page, pageSize, order, sort);\r\n\r\n                var getPaginate" +
                    "dResponse = _mapper.Map<IEnumerable<Core.Models.");
            
            #line 47 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(">, IEnumerable<Response.List.");
            
            #line 47 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("ItemList>>(");
            
            #line 47 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(@"Collection);

                result = Ok(getPaginatedResponse);
            }
            else
            {
                result = BadRequest(""Invalid filters"");
            }

            return result;
        }

        [HttpGet(""{id}"")]
        public async Task<ActionResult<Response.Read.");
            
            #line 60 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Item>> GetFullById(int id)\r\n        {\r\n            var ");
            
            #line 62 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 62 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetFullById(id);\r\n          \r\n            var getFullByIdResponse = _mapp" +
                    "er.Map<Core.Models.");
            
            #line 64 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(", Response.Read.");
            
            #line 64 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Item>(");
            
            #line 64 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            return Ok(getFullByIdResponse);\r\n        }\r\n\r\n        [HttpPost" +
                    "(\"\")]\r\n        public async Task<ActionResult<Response.Read.");
            
            #line 70 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Item>> Create([FromBody] Request.Create.");
            
            #line 70 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("RequestCreate requestCreate)\r\n        {\r\n            var validator = new Request." +
                    "Create.");
            
            #line 72 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("RequestCreateValidator();\r\n            var validationResult = await validator.Val" +
                    "idateAsync(requestCreate);\r\n\r\n            if (!validationResult.IsValid)\r\n      " +
                    "          return BadRequest(validationResult.Errors);\r\n\r\n            var ");
            
            #line 78 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("ToCreate = _mapper.Map<Request.Create.");
            
            #line 78 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("RequestCreate, Core.Models.");
            
            #line 78 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(">(requestCreate);\r\n\r\n            var access_token = await HttpContext.GetTokenAsy" +
                    "nc(\"access_token\");\r\n\r\n            var new");
            
            #line 82 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 82 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.Create(");
            
            #line 82 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("ToCreate, access_token);\r\n\r\n            var ");
            
            #line 84 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 84 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetFullById(new");
            
            #line 84 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(".Id);\r\n\r\n            var createResponse = _mapper.Map<Core.Models.");
            
            #line 86 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(", Response.Read.");
            
            #line 86 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Item>(");
            
            #line 86 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            return Ok(createResponse);\r\n        }\r\n\r\n        [HttpPut(\"{id}" +
                    "\")]\r\n        public async Task<ActionResult<Response.Read.");
            
            #line 92 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Item>> Update(int id, [FromBody] Request.Update.");
            
            #line 92 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("RequestUpdate requestUpdate)\r\n        {\r\n            var validator = new Request." +
                    "Update.");
            
            #line 94 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("RequestUpdateValidator();\r\n            var validationResult = await validator.Val" +
                    "idateAsync(requestUpdate);\r\n\r\n            if (!validationResult.IsValid)\r\n      " +
                    "          return BadRequest(validationResult.Errors);\r\n\r\n            var ");
            
            #line 100 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("ToBeUpdated = await _");
            
            #line 100 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetFullById(id);\r\n\r\n            if (");
            
            #line 102 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("ToBeUpdated == null)\r\n                return NotFound();\r\n\r\n            var ");
            
            #line 105 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(" = _mapper.Map<Request.Update.");
            
            #line 105 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("RequestUpdate, Core.Models.");
            
            #line 105 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(">(requestUpdate);\r\n\r\n            var access_token = await HttpContext.GetTokenAsy" +
                    "nc(\"access_token\");\r\n\r\n            await _");
            
            #line 109 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.Update(");
            
            #line 109 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("ToBeUpdated, ");
            
            #line 109 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(", access_token);\r\n\r\n            var updated");
            
            #line 111 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 111 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetFullById(id);\r\n\r\n            var updateResponse = _mapper.Map<Core.Mod" +
                    "els.");
            
            #line 113 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(", Response.Read.");
            
            #line 113 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("Item>(updated");
            
            #line 113 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n            return Ok(updateResponse);\r\n        }\r\n\r\n        [HttpDelete(\"{" +
                    "id}\")]\r\n        public async Task<IActionResult> Delete(int id)\r\n        {\r\n    " +
                    "        if (id == 0)\r\n                return BadRequest();\r\n\r\n            var ");
            
            #line 124 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(" = await _");
            
            #line 124 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.GetById(id);\r\n\r\n            if (");
            
            #line 126 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n                return NotFound();\r\n\r\n            var access_token = a" +
                    "wait HttpContext.GetTokenAsync(\"access_token\");\r\n\r\n            await _");
            
            #line 131 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write("Service.Delete(");
            
            #line 131 "D:\Proyectos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\ApiEntityController.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.FirstLetterToLower(tableName)));
            
            #line default
            #line hidden
            this.Write(", access_token);\r\n\r\n            return NoContent();  \r\n        } \r\n    } \r\n}\r\n\r\n");
            this.Write(" \r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ApiEntityControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
