// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4CodeGenerator.MSSQL2CSHARP.Templates.SQLSERVER.NETCORE.CSHARP
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using T4CodeGenerator.MSSQL2CSHARP.Database;
    using T4CodeGenerator.MSSQL2CSHARP.Helpers;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class CoreModel : CoreModelBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 1 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
      
// Se repite por cada tabla en la base de datos
string tableName = Configuration.TableName;

            
            #line default
            #line hidden
            this.Write(" \r\n\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Collections.O" +
                    "bjectModel;\r\n\r\nnamespace Core.Models\r\n{\r\n    public partial class ");
            
            #line 12 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("\r\n    {  \r\n");
            
            #line 14 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
 
    // Se repite por cada columna de la tabla (NO ForeingKey)
    foreach(string columnName in Configuration.MSSQL.GetRepeatersColumns(tableName))
    {
        InformationSchemaColumns informationSchemaColumn = Configuration.MSSQL.GetMetadataByTableNameAndColumnName(tableName, columnName);

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 20 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.MSSQL.DataTypeMapping(informationSchemaColumn.DATA_TYPE)));
            
            #line default
            #line hidden
            
            #line 20 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.IS_NULLABLE ? "?" : string.Empty));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 20 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 21 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
  
    }
    // Se repite por cada ForeingKey de la tabla
    foreach(InformationSchemaColumns informationSchemaColumn in Configuration.MSSQL.GetRepeatersReferencedTablesInformationFromThis(tableName, Configuration.ExcludedClasses))
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 27 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Configuration.MSSQL.DataTypeMapping(informationSchemaColumn.DATA_TYPE)));
            
            #line default
            #line hidden
            
            #line 27 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.IS_NULLABLE ? "?" : string.Empty));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.COLUMN_NAME));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n        public ");
            
            #line 28 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.REFERENCED_TABLE_NAME));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 28 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.RemoveId(informationSchemaColumn.COLUMN_NAME)));
            
            #line default
            #line hidden
            this.Write("  { get; set; }\r\n");
            
            #line 29 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
       
    }

    List<InformationSchemaColumns> informationSchemaColumnList = Configuration.MSSQL.GetRepeatersReferencedTablesNamesToThis(tableName, Configuration.ExcludedClasses);

    // Se repite por cada tabla que hace referencia a esta tabla
    foreach(InformationSchemaColumns informationSchemaColumn in informationSchemaColumnList)
    {
        // Las referencias a la misma tabla no se manejan como colecciones
        if (informationSchemaColumn.PARENT_TABLE_NAME != informationSchemaColumn.REFERENCED_TABLE_NAME) 
        {
            if (informationSchemaColumnList.FindAll(isc => isc.TABLE_NAME == informationSchemaColumn.TABLE_NAME).Count() > 1) 
            {

            
            #line default
            #line hidden
            this.Write("        public ICollection<");
            
            #line 43 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.TABLE_NAME));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 43 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Utils.RemoveId(informationSchemaColumn.COLUMN_NAME)));
            
            #line default
            #line hidden
            this.Write("Collection { get; set; } \r\n");
            
            #line 44 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
    
            }
            else 
            {

            
            #line default
            #line hidden
            this.Write("        public ICollection<");
            
            #line 49 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.TABLE_NAME));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 49 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(informationSchemaColumn.TABLE_NAME));
            
            #line default
            #line hidden
            this.Write("Collection { get; set; }\r\n");
            
            #line 50 "C:\Users\ncustodio\source\repos\T4CodeGenerator\T4CodeGenerator.MSSQL2CSHARP\Templates\SQLSERVER\NETCORE\CSHARP\CoreModel.tt"
 
            }    
        }  
    }

            
            #line default
            #line hidden
            this.Write("    }\r\n}     \r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class CoreModelBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
